Repository WesternFriend/westernfriend.org, pull requests merged in 2024-09, with the labels that each got.

#1109 Fix verbose names and improve search indexes
  .devcontainer/devcontainer.json
  community/models.py
  documents/models.py
  events/models.py
  library/models.py
  magazine/migrations/0034_alter_magazinearticle_options_and_more.py
  magazine/models.py
  memorials/models.py
Labels: enhancement, configuration changes, Review effort [1-5]: 3

#1119 Added metadata to events page
  events/templates/events/event.html
Labels: enhancement, Review effort [1-5]: 2, documentation

#1120 Added metadata using schema.org to contacts
  contact/templates/contact/contact.html
Labels: enhancement, Review effort [1-5]: 3, documentation
